import { NextResponse } from 'next/server';

export async function GET() {
  // Simulating database data 
  const shifts = [
    {
      shift_id: 1,
      employee_id: 1,
      employee_name: 'John Doe',
      position: 'Manager',
      department: 'Front Desk',
      shift_date: '2023-10-14',
      start_time: '08:00',
      end_time: '16:00',
    },
    {
      shift_id: 2,
      employee_id: 2,
      employee_name: 'Jane Smith',
      position: 'Receptionist',
      department: 'Front Desk',
      shift_date: '2023-10-14',
      start_time: '08:00',
      end_time: '16:00',
    },
    {
      shift_id: 3,
      employee_id: 3,
      employee_name: 'Alice Johnson',
      position: 'Housekeeper',
      department: 'Housekeeping',
      shift_date: '2023-10-14',
      start_time: '09:00',
      end_time: '17:00',
    },
    {
      shift_id: 4,
      employee_id: 4,
      employee_name: 'Bob Brown',
      position: 'Maintenance',
      department: 'Maintenance',
      shift_date: '2023-10-14',
      start_time: '10:00',
      end_time: '18:00',
    },
    {
      shift_id: 5,
      employee_id: 5,
      employee_name: 'Charlie Davis',
      position: 'Chef',
      department: 'Kitchen',
      shift_date: '2023-10-14',
      start_time: '11:00',
      end_time: '19:00',
    },
    {
      shift_id: 6,
      employee_id: 6,
      employee_name: 'Diana Wilson',
      position: 'Waitstaff',
      department: 'Dining',
      shift_date: '2023-10-14',
      start_time: '12:00',
      end_time: '20:00',
    },
    {
      shift_id: 7,
      employee_id: 7,
      employee_name: 'Ethan Martinez',
      position: 'Bartender',
      department: 'Dining',
      shift_date: '2023-10-14',
      start_time: '13:00',
      end_time: '21:00',
    },
    {
      shift_id: 8,
      employee_id: 8,
      employee_name: 'Fiona Garcia',
      position: 'Concierge',
      department: 'Guest Services',
      shift_date: '2023-10-14',
      start_time: '14:00',
      end_time: '22:00',
    },
    // More shifts for other dates
    {
      shift_id: 11,
      employee_id: 1,
      employee_name: 'John Doe',
      position: 'Manager',
      department: 'Front Desk',
      shift_date: '2023-10-15',
      start_time: '08:00',
      end_time: '16:00',
    },
    {
      shift_id: 12,
      employee_id: 2,
      employee_name: 'Jane Smith',
      position: 'Receptionist',
      department: 'Front Desk',
      shift_date: '2023-10-15',
      start_time: '08:00',
      end_time: '16:00',
    },
    {
      shift_id: 21,
      employee_id: 1,
      employee_name: 'John Doe',
      position: 'Manager',
      department: 'Front Desk',
      shift_date: '2023-10-16',
      start_time: '08:00',
      end_time: '16:00',
    },
    {
      shift_id: 22,
      employee_id: 2,
      employee_name: 'Jane Smith',
      position: 'Receptionist',
      department: 'Front Desk',
      shift_date: '2023-10-16',
      start_time: '08:00',
      end_time: '16:00',
    }
  ];

  return NextResponse.json(shifts);
}
